name: Release

on:
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/test.yml

  release:
    needs: test
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    uses: macieklamberski/kvalita/.github/workflows/shared-release.yml@main
    with:
      bun-version: "1.2.20"
    secrets: inherit
